version: "3"
services:
  db:
    image: postgres:11
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test_app
  redis:
    image: redis:3.2.4-alpine
    ports:
      - 63795:6379
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
  adminer:
    image: adminer
    ports:
      - 8585:8080
